# Generated by Django 4.2.1 on 2024-04-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptomis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('cin', models.CharField(max_length=15, verbose_name='cin')),
                ('symptom1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symtpom1', to='authentic.symptomis')),
                ('symptom2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symtpom2', to='authentic.symptomis')),
                ('symptom3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symtpom3', to='authentic.symptomis')),
                ('symptom4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symtpom4', to='authentic.symptomis')),
                ('symptom5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symtpom5', to='authentic.symptomis')),
            ],
        ),
    ]
