# Generated by Django 4.2.1 on 2024-04-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag', models.CharField(max_length=120, verbose_name='diag')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='authentic.diagnosis')),
            ],
        ),
    ]
